load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load("@rules_rust//rust:defs.bzl", "rustfmt_test")
load("@workspace_version//:version.bzl", "WORKSPACE_VERSION")

rust_library(
    name = "openshell-supervisor-middleware-builtins",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    version = WORKSPACE_VERSION,
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "openshell-supervisor-middleware-builtins_test",
    crate = ":openshell-supervisor-middleware-builtins",
    deps = all_crate_deps(normal_dev = True),
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [
        ":openshell-supervisor-middleware-builtins",
        ":openshell-supervisor-middleware-builtins_test",
    ],
    visibility = ["//crates:__pkg__"],
)
