load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_proc_macro.bzl", "rust_proc_macro")
load("@rules_rust//rust:defs.bzl", "rustfmt_test")

rust_proc_macro(
    name = "openshell-server-macros",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [":openshell-server-macros"],
    visibility = ["//crates:__pkg__"],
)
