load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "openshell-driver-kubernetes",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
    ),
    aliases = aliases(),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_binary(
    name = "openshell-driver-kubernetes_bin",
    srcs = ["src/main.rs"],
    aliases = aliases(),
    binary_name = "openshell-driver-kubernetes",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True) + [":openshell-driver-kubernetes"],
)

rust_test(
    name = "openshell-driver-kubernetes_test",
    crate = ":openshell-driver-kubernetes",
    deps = all_crate_deps(normal_dev = True),
)
