// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Auth endpoint for edge-proxy browser-based login.
//!
//! When the CLI runs `gateway add` or `gateway login`, it opens the user's
//! browser to `GET /auth/connect?callback_port=<port>`. The edge proxy
//! (e.g., Cloudflare Access) intercepts the request and shows its `IdP` login
//! page. After authentication, the proxy sets the `CF_Authorization` cookie
//! and proxies the request to this endpoint.
//!
//! The handler reads the `CF_Authorization` cookie from the request headers
//! (required because the cookie is typically `HttpOnly`) and serves a styled
//! confirmation page. When the user clicks "Connect", JavaScript POSTs
//! the token to `http://127.0.0.1:<callback_port>/callback`, where the
//! CLI's ephemeral localhost server captures and stores the token.

use axum::{
    Json, Router,
    extract::{Query, State},
    http::{HeaderMap, StatusCode, Uri},
    response::{Html, IntoResponse},
    routing::get,
};
use http::header;
use serde::Deserialize;
use std::sync::Arc;

use crate::ServerState;

/// Validate that a confirmation code matches the CLI-generated format.
///
/// Codes are 3 alphanumeric characters, a dash, then 4 alphanumeric characters
/// (e.g., "AB7-X9KM"). The CLI generates these from the charset `[A-Z2-9]`.
fn is_valid_code(code: &str) -> bool {
    let bytes = code.as_bytes();
    bytes.len() == 8
        && bytes[3] == b'-'
        && bytes[..3]
            .iter()
            .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit())
        && bytes[4..]
            .iter()
            .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit())
}

#[derive(Deserialize)]
struct ConnectParams {
    callback_port: u16,
    /// One-time confirmation code generated by the CLI. Displayed on the
    /// connect page so the user can verify it matches their terminal before
    /// clicking Connect. Sent back in the XHR POST to the CLI callback
    /// server for cryptographic binding.
    code: String,
}

/// Create the auth router.
pub fn router(state: Arc<ServerState>) -> Router {
    Router::new()
        .route("/auth/connect", get(auth_connect))
        .route("/auth/oidc-config", get(oidc_config_handler))
        .route("/.well-known/jwks.json", get(gateway_jwks_handler))
        .route(
            "/.well-known/openid-configuration",
            get(gateway_discovery_handler),
        )
        .with_state(state)
}

/// Publish OIDC-shaped discovery metadata for extension services.
///
/// This lets an extension be configured with only the trusted gateway URL:
/// it learns the exact expected `iss` and the `jwks_uri` from one document
/// instead of having both provisioned separately.
///
/// Like the equivalent Kubernetes endpoint, this is OIDC-shaped rather than
/// OIDC-compliant: `issuer` is the gateway identity (`openshell-gateway:<id>`),
/// not the URL this document is served from. Verifiers must compare `iss`
/// against that value, and must not infer trust from the document's location
/// alone. The serving TLS connection is what authenticates the gateway.
async fn gateway_discovery_handler(
    State(state): State<Arc<ServerState>>,
    headers: HeaderMap,
    uri: Uri,
) -> impl IntoResponse {
    gateway_discovery_response(
        state.sandbox_jwt_authenticator.as_deref(),
        &document_base_url(&headers, &uri),
    )
}

/// Reconstruct the externally visible base URL for absolute discovery links.
///
/// HTTP/1.1 carries `Host`; HTTP/2 carries `:authority`, which axum surfaces
/// on the request URI. A terminating proxy may report the original scheme in
/// `X-Forwarded-Proto`; otherwise assume TLS, since the extension contract
/// requires fetching this document over an authenticated connection.
fn document_base_url(headers: &HeaderMap, uri: &Uri) -> Option<String> {
    let authority = headers
        .get(header::HOST)
        .and_then(|value| value.to_str().ok())
        .filter(|host| !host.is_empty())
        .map(ToString::to_string)
        .or_else(|| uri.authority().map(ToString::to_string))?;
    let scheme = headers
        .get("x-forwarded-proto")
        .and_then(|value| value.to_str().ok())
        .and_then(|proto| proto.split(',').next())
        .map(str::trim)
        .filter(|proto| !proto.is_empty())
        .unwrap_or("https");
    Some(format!("{scheme}://{authority}"))
}

fn gateway_discovery_response(
    authenticator: Option<&crate::auth::sandbox_jwt::SandboxJwtAuthenticator>,
    base_url: &Option<String>,
) -> axum::response::Response {
    let Some(authenticator) = authenticator else {
        return StatusCode::NOT_FOUND.into_response();
    };
    let Some(base_url) = base_url else {
        // Without a usable authority the `jwks_uri` cannot be absolute, and a
        // relative value would be worse than none: a verifier could resolve it
        // against the wrong origin.
        return StatusCode::BAD_REQUEST.into_response();
    };
    Json(serde_json::json!({
        "issuer": authenticator.issuer(),
        "jwks_uri": format!("{base_url}/.well-known/jwks.json"),
        "id_token_signing_alg_values_supported": ["EdDSA"],
        "response_types_supported": ["id_token"],
        "subject_types_supported": ["public"],
        "scopes_supported": ["openid"],
        "claims_supported": [
            "iss", "aud", "sub", "iat", "exp", "jti", "caller_kind", "sandbox_id"
        ],
    }))
    .into_response()
}

/// Publish the gateway's JWT verification key for extension services.
///
/// Public keys are not secret. The HTTPS connection authenticates the
/// gateway from which an integration bootstraps this document; integrations
/// then cache keys by `kid` and refresh when an unfamiliar `kid` appears.
async fn gateway_jwks_handler(State(state): State<Arc<ServerState>>) -> impl IntoResponse {
    gateway_jwks_response(state.sandbox_jwt_authenticator.as_deref())
}

fn gateway_jwks_response(
    authenticator: Option<&crate::auth::sandbox_jwt::SandboxJwtAuthenticator>,
) -> axum::response::Response {
    authenticator.map_or_else(
        || StatusCode::NOT_FOUND.into_response(),
        |authenticator| Json(authenticator.jwks()).into_response(),
    )
}

/// OIDC configuration discovery endpoint.
///
/// Returns the OIDC issuer and audience when OIDC is configured on the server,
/// so CLI clients can auto-discover settings during `gateway add`.
async fn oidc_config_handler(State(state): State<Arc<ServerState>>) -> impl IntoResponse {
    state.config.oidc.as_ref().map_or_else(
        || StatusCode::NOT_FOUND.into_response(),
        |oidc| {
            Json(serde_json::json!({
                "issuer": oidc.issuer,
                "audience": oidc.audience,
            }))
            .into_response()
        },
    )
}

/// Handle the auth connect request.
///
/// Reads `CF_Authorization` from the cookie header (server-side extraction
/// handles `HttpOnly` cookies) and serves either a waiting page or a
/// styled confirmation page with the token embedded.
async fn auth_connect(
    State(state): State<Arc<ServerState>>,
    Query(params): Query<ConnectParams>,
    headers: HeaderMap,
) -> impl IntoResponse {
    // Reject codes that don't match the CLI-generated format to prevent
    // reflected XSS via crafted URLs.
    if !is_valid_code(&params.code) {
        return Html(
            "<html><body><p>Invalid confirmation code format.</p></body></html>".to_string(),
        )
        .into_response();
    }

    let cf_token = headers
        .get("cookie")
        .and_then(|v| v.to_str().ok())
        .and_then(|cookies| extract_cookie(cookies, "CF_Authorization"));

    // Prefer the Host header (set by Cloudflare Tunnel / reverse proxies)
    // so the page shows the external URL the user actually connected through
    // rather than the internal bind address (e.g. 0.0.0.0:8080).
    let gateway_display = headers
        .get("x-forwarded-host")
        .or_else(|| headers.get("host"))
        .and_then(|v| v.to_str().ok())
        .map_or_else(|| state.config.bind_address.to_string(), String::from);

    let safe_gateway = html_escape(&gateway_display);

    if let Some(token) = cf_token {
        let nonce = uuid::Uuid::new_v4().to_string();
        let csp = format!(
            "default-src 'none'; script-src 'nonce-{nonce}'; style-src 'unsafe-inline'; connect-src http://127.0.0.1:*"
        );
        (
            [(header::CONTENT_SECURITY_POLICY, csp)],
            Html(render_connect_page(
                &safe_gateway,
                params.callback_port,
                &token,
                &params.code,
                &nonce,
            )),
        )
            .into_response()
    } else {
        let csp = "default-src 'none'; style-src 'unsafe-inline'".to_string();
        (
            [(header::CONTENT_SECURITY_POLICY, csp)],
            Html(render_waiting_page(params.callback_port, &params.code)),
        )
            .into_response()
    }
}

/// Extract a named cookie value from a `Cookie` header string.
fn extract_cookie(cookies: &str, name: &str) -> Option<String> {
    cookies.split(';').find_map(|c| {
        let mut parts = c.trim().splitn(2, '=');
        let key = parts.next()?.trim();
        let val = parts.next()?.trim();
        if key == name {
            Some(val.to_string())
        } else {
            None
        }
    })
}

/// Render the styled confirmation page with the edge auth token embedded.
///
/// The page displays the confirmation code so the user can verify it matches
/// their terminal. Clicking "Connect" sends an XHR POST (not a redirect) to
/// the CLI's localhost callback server, keeping the token out of browser
/// history and the URL bar.
fn render_connect_page(
    gateway_addr: &str,
    callback_port: u16,
    cf_token: &str,
    code: &str,
    nonce: &str,
) -> String {
    // Use JSON serialization for JS-safe string embedding — handles all
    // edge cases including \n, \r, U+2028, U+2029 that break JS string
    // literals. serde_json::to_string produces a quoted JSON string
    // (e.g., "value") which is a valid JS string literal.
    //
    // We additionally escape < and > to \u003c / \u003e because while
    // they're valid in JSON, they're dangerous inside an HTML <script>
    // block (the HTML parser sees </script> before the JS parser runs).
    let json_token = serde_json::to_string(cf_token)
        .unwrap_or_else(|_| "\"\"".to_string())
        .replace('<', "\\u003c")
        .replace('>', "\\u003e");
    let json_code = serde_json::to_string(code)
        .unwrap_or_else(|_| "\"\"".to_string())
        .replace('<', "\\u003c")
        .replace('>', "\\u003e");

    // HTML-safe version of the code for display in the page body.
    let html_code = html_escape(code);

    let version = openshell_core::VERSION;

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OpenShell — Connect to Gateway</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', monospace;
            background: #f5f5f5;
            color: #1a1a1a;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }}
        .card {{
            background: #ffffff;
            border: 1px solid #e0e0e0;
            border-radius: 12px;
            padding: 48px;
            max-width: 480px;
            width: 100%;
            text-align: center;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }}
        .logo {{
            font-size: 28px;
            font-weight: 700;
            color: #76b900;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }}
        .subtitle {{
            color: #666;
            font-size: 14px;
            margin-bottom: 32px;
        }}
        .info {{
            background: #fafafa;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 24px;
            text-align: left;
        }}
        .info-row {{
            display: flex;
            justify-content: space-between;
            padding: 6px 0;
            font-size: 13px;
        }}
        .info-label {{ color: #888; }}
        .info-value {{
            color: #333;
            font-weight: 500;
            word-break: break-all;
            text-align: right;
            max-width: 60%;
        }}
        .code-box {{
            background: #fafafa;
            border: 2px solid #76b900;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 24px;
        }}
        .code-label {{
            color: #666;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 8px;
        }}
        .code-value {{
            font-size: 32px;
            font-weight: 700;
            color: #76b900;
            letter-spacing: 4px;
        }}
        .code-hint {{
            color: #888;
            font-size: 11px;
            margin-top: 8px;
        }}
        .connect-btn {{
            background: #76b900;
            color: #ffffff;
            border: none;
            border-radius: 8px;
            padding: 14px 32px;
            font-size: 15px;
            font-weight: 600;
            font-family: inherit;
            cursor: pointer;
            width: 100%;
            transition: background 0.15s;
        }}
        .connect-btn:hover {{ background: #8ad100; }}
        .connect-btn:active {{ background: #6aa000; }}
        .connect-btn:disabled {{
            background: #ccc;
            color: #888;
            cursor: not-allowed;
        }}
        .hint {{
            color: #888;
            font-size: 12px;
            margin-top: 16px;
        }}
        .status {{
            margin-top: 16px;
            font-size: 13px;
            min-height: 20px;
        }}
        .status-ok {{ color: #76b900; }}
        .status-err {{ color: #d32f2f; }}
    </style>
</head>
<body>
    <div class="card">
        <div class="logo">OpenShell</div>
        <div class="subtitle">Connect to Gateway</div>
        <div class="code-box">
            <div class="code-label">Confirmation Code</div>
            <div class="code-value">{html_code}</div>
            <div class="code-hint">Verify this matches the code shown in your terminal</div>
        </div>
        <div class="info">
            <div class="info-row">
                <span class="info-label">Gateway</span>
                <span class="info-value">{gateway_addr}</span>
            </div>
            <div class="info-row">
                <span class="info-label">Version</span>
                <span class="info-value">v{version}</span>
            </div>
        </div>
        <button class="connect-btn" id="connectBtn" onclick="connect()">
            Connect to Gateway
        </button>
        <div class="hint">
            This will authorize the OpenShell CLI to connect to this gateway.
        </div>
        <div class="status" id="status"></div>
    </div>
    <script nonce="{nonce}">
        var token = {json_token};
        var code = {json_code};
        var port = {callback_port};
        function connect() {{
            var btn = document.getElementById('connectBtn');
            var status = document.getElementById('status');
            btn.disabled = true;
            btn.textContent = 'Connecting...';
            status.textContent = '';
            status.className = 'status';

            fetch('http://127.0.0.1:' + port + '/callback', {{
                method: 'POST',
                headers: {{ 'Content-Type': 'application/json' }},
                body: JSON.stringify({{ token: token, code: code }})
            }})
            .then(function(resp) {{ return resp.json(); }})
            .then(function(data) {{
                if (data.ok) {{
                    btn.textContent = 'Connected';
                    status.className = 'status status-ok';
                    status.textContent = 'Connected! You can close this tab.';
                }} else {{
                    btn.disabled = false;
                    btn.textContent = 'Connect to Gateway';
                    status.className = 'status status-err';
                    status.textContent = data.error || 'Connection failed. Please try again.';
                }}
            }})
            .catch(function(err) {{
                btn.disabled = false;
                btn.textContent = 'Connect to Gateway';
                status.className = 'status status-err';
                status.textContent = 'Could not reach the CLI. Is openshell still running?';
            }});
        }}
    </script>
</body>
</html>"#,
    )
}

/// Minimal HTML attribute escaping for untrusted values.
///
/// Escapes `&`, `"`, `'`, `<`, and `>` so the value is safe for embedding
/// inside a quoted HTML attribute.
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#x27;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            c => out.push(c),
        }
    }
    out
}

/// Render a waiting page shown when the edge proxy auth cookie is not yet present.
///
/// This can happen if the edge proxy hasn't completed authentication yet. The
/// page auto-reloads after a short delay to pick up the cookie once login
/// finishes. The `code` parameter is preserved across reloads.
fn render_waiting_page(callback_port: u16, code: &str) -> String {
    let safe_code = html_escape(code);
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="2;url=/auth/connect?callback_port={callback_port}&amp;code={safe_code}">
    <title>OpenShell — Authenticating</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', monospace;
            background: #f5f5f5;
            color: #1a1a1a;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }}
        .card {{
            background: #ffffff;
            border: 1px solid #e0e0e0;
            border-radius: 12px;
            padding: 48px;
            max-width: 480px;
            width: 100%;
            text-align: center;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }}
        .logo {{
            font-size: 28px;
            font-weight: 700;
            color: #76b900;
            margin-bottom: 8px;
        }}
        .message {{
            color: #666;
            font-size: 14px;
            margin-top: 16px;
        }}
        .spinner {{
            margin: 24px auto;
            width: 32px;
            height: 32px;
            border: 3px solid #e0e0e0;
            border-top-color: #76b900;
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
        }}
        @keyframes spin {{
            to {{ transform: rotate(360deg); }}
        }}
    </style>
</head>
<body>
    <div class="card">
        <div class="logo">OpenShell</div>
        <div class="spinner"></div>
        <div class="message">Authenticating...</div>
    </div>
</body>
</html>"#,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::to_bytes;
    use openshell_bootstrap::jwt::generate_jwt_key;

    #[test]
    fn extract_cookie_finds_value() {
        let cookies = "other=foo; CF_Authorization=eyJhbGciOiJSUzI1NiJ9.test; bar=baz";
        assert_eq!(
            extract_cookie(cookies, "CF_Authorization"),
            Some("eyJhbGciOiJSUzI1NiJ9.test".to_string())
        );
    }

    #[test]
    fn extract_cookie_returns_none_when_missing() {
        let cookies = "other=foo; bar=baz";
        assert_eq!(extract_cookie(cookies, "CF_Authorization"), None);
    }

    #[test]
    fn extract_cookie_handles_single_cookie() {
        let cookies = "CF_Authorization=my-token";
        assert_eq!(
            extract_cookie(cookies, "CF_Authorization"),
            Some("my-token".to_string())
        );
    }

    #[test]
    fn render_connect_page_contains_token_and_code() {
        let html = render_connect_page(
            "gateway.example.com:8080",
            12345,
            "test-jwt-token",
            "ABC-1234",
            "test-nonce",
        );
        assert!(html.contains("test-jwt-token"));
        assert!(html.contains("12345"));
        assert!(html.contains("gateway.example.com:8080"));
        assert!(html.contains("OpenShell"));
        assert!(html.contains("ABC-1234"));
        // Should use fetch(), not window.location.href
        assert!(html.contains("fetch("));
        assert!(!html.contains("window.location.href"));
        // Should POST with JSON
        assert!(html.contains("method: 'POST'"));
        assert!(html.contains("JSON.stringify"));
        // CSP nonce should be on the script tag
        assert!(html.contains("nonce=\"test-nonce\""));
    }

    #[test]
    fn render_connect_page_escapes_special_chars() {
        let html = render_connect_page(
            "gw",
            1234,
            "token<script>alert('xss')</script>",
            "ABC-1234",
            "nonce",
        );
        // < and > should be escaped via JSON encoding (\u003c)
        assert!(!html.contains("<script>alert"));
    }

    #[test]
    fn render_connect_page_includes_code_in_js_payload() {
        let html = render_connect_page("gw", 1234, "jwt", "XY7-9KLM", "nonce");
        // The JS should send the code in the JSON payload (now JSON-encoded)
        assert!(html.contains(r#"var code = "XY7-9KLM""#));
        assert!(html.contains("code: code"));
    }

    #[test]
    fn is_valid_code_accepts_valid_format() {
        assert!(is_valid_code("AB7-X9KM"));
        assert!(is_valid_code("222-AAAA"));
        assert!(is_valid_code("ZZZ-9999"));
    }

    #[test]
    fn is_valid_code_rejects_invalid_format() {
        assert!(!is_valid_code(""));
        assert!(!is_valid_code("too-long-code"));
        assert!(!is_valid_code("abc-defg")); // lowercase
        assert!(!is_valid_code("AB7X9KLM")); // no dash
        assert!(!is_valid_code("AB7-9KL")); // too short
        assert!(!is_valid_code("x\u{2028};fetch('//evil')//")); // XSS payload
    }

    #[test]
    fn render_waiting_page_has_auto_refresh_with_code() {
        let html = render_waiting_page(12345, "ABC-1234");
        assert!(html.contains("meta http-equiv=\"refresh\""));
        assert!(html.contains("callback_port=12345"));
        assert!(html.contains("code=ABC-1234"));
    }

    #[test]
    fn render_waiting_page_escapes_code() {
        let html = render_waiting_page(1234, "x\"onload=\"alert(1)");
        // The double quote should be escaped so it can't break out of the
        // meta-refresh content attribute.
        assert!(!html.contains("x\"onload"));
        assert!(html.contains("&quot;"));
    }

    #[test]
    fn html_escape_basic() {
        assert_eq!(html_escape("hello"), "hello");
        assert_eq!(html_escape("<b>bold</b>"), "&lt;b&gt;bold&lt;/b&gt;");
        assert_eq!(html_escape("a&b"), "a&amp;b");
        assert_eq!(html_escape("a\"b"), "a&quot;b");
        assert_eq!(html_escape("a'b"), "a&#x27;b");
    }

    #[test]
    fn jwks_response_publishes_configured_gateway_key() {
        let material = generate_jwt_key().expect("key");
        let authenticator = crate::auth::sandbox_jwt::SandboxJwtAuthenticator::from_pem(
            material.public_key_pem.as_bytes(),
            material.kid.clone(),
            "gateway-a",
        )
        .expect("authenticator");

        let response = gateway_jwks_response(Some(&authenticator));
        assert_eq!(response.status(), StatusCode::OK);
        let key = &authenticator.jwks().keys[0];
        assert_eq!(key.kid, material.kid);
        assert_eq!(key.kty, "OKP");
        assert_eq!(key.crv, "Ed25519");
        assert_eq!(key.alg, "EdDSA");
        assert_eq!(key.key_use, "sig");
    }

    #[test]
    fn jwks_response_is_not_found_without_gateway_key() {
        assert_eq!(gateway_jwks_response(None).status(), StatusCode::NOT_FOUND);
    }

    fn test_authenticator() -> crate::auth::sandbox_jwt::SandboxJwtAuthenticator {
        let material = generate_jwt_key().expect("key");
        crate::auth::sandbox_jwt::SandboxJwtAuthenticator::from_pem(
            material.public_key_pem.as_bytes(),
            material.kid,
            "gateway-a",
        )
        .expect("authenticator")
    }

    #[tokio::test]
    async fn discovery_document_advertises_issuer_identity_and_absolute_jwks_uri() {
        let authenticator = test_authenticator();
        let response = gateway_discovery_response(
            Some(&authenticator),
            &Some("https://gateway.example:8443".to_string()),
        );
        assert_eq!(response.status(), StatusCode::OK);

        let body = to_bytes(response.into_body(), 64 * 1024)
            .await
            .expect("body");
        let document: serde_json::Value = serde_json::from_slice(&body).expect("json");

        // The issuer is the gateway identity, not the serving URL. Extensions
        // compare `iss` against this exact value.
        assert_eq!(document["issuer"], "openshell-gateway:gateway-a");
        assert_eq!(
            document["jwks_uri"],
            "https://gateway.example:8443/.well-known/jwks.json"
        );
        assert_eq!(
            document["id_token_signing_alg_values_supported"][0],
            "EdDSA"
        );
    }

    #[test]
    fn discovery_document_requires_a_key_and_a_resolvable_authority() {
        assert_eq!(
            gateway_discovery_response(None, &Some("https://gateway.example".to_string())).status(),
            StatusCode::NOT_FOUND
        );
        // A relative jwks_uri could be resolved against the wrong origin, so
        // refuse to emit a document rather than emit an ambiguous one.
        assert_eq!(
            gateway_discovery_response(Some(&test_authenticator()), &None).status(),
            StatusCode::BAD_REQUEST
        );
    }

    #[test]
    fn base_url_prefers_host_header_and_honours_forwarded_scheme() {
        let mut headers = HeaderMap::new();
        headers.insert(header::HOST, "gateway.example:8443".parse().unwrap());
        assert_eq!(
            document_base_url(&headers, &Uri::from_static("/")),
            Some("https://gateway.example:8443".to_string())
        );

        headers.insert("x-forwarded-proto", "http, https".parse().unwrap());
        assert_eq!(
            document_base_url(&headers, &Uri::from_static("/")),
            Some("http://gateway.example:8443".to_string())
        );

        // HTTP/2 has no Host header; axum surfaces `:authority` on the URI.
        assert_eq!(
            document_base_url(
                &HeaderMap::new(),
                &Uri::from_static("https://h2.example/.well-known/openid-configuration")
            ),
            Some("https://h2.example".to_string())
        );
        assert_eq!(
            document_base_url(&HeaderMap::new(), &Uri::from_static("/")),
            None
        );
    }
}
