load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "openshell-ocsf",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "openshell-ocsf_test",
    crate = ":openshell-ocsf",
    data = glob(["schemas/**/*"]),
    rustc_env = {
        "CARGO_MANIFEST_DIR": "crates/openshell-ocsf",
    },
    deps = all_crate_deps(normal_dev = True),
)
