load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load("@rules_rust//rust:defs.bzl", "rustfmt_test")

rust_library(
    name = "openshell-otel",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "openshell-otel_test",
    crate = ":openshell-otel",
    deps = all_crate_deps(normal_dev = True),
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [
        ":openshell-otel",
        ":openshell-otel_test",
    ],
    visibility = ["//crates:__pkg__"],
)
