# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build Runtime Binaries

on:
  workflow_call:
    inputs:
      cargo-version:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: ""
      checkout-ref:
        required: false
        type: string
        default: ""
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - triple: x86_64-unknown-linux-musl
            runner: linux-amd64-cpu8
            package: openshell-sandbox
            binary: openshell-sandbox
            interpreter: none
          - triple: x86_64-unknown-linux-gnu
            runner: linux-amd64-cpu8
            package: openshell-supervisor
            binary: openshell-supervisor
            interpreter: /lib64/ld-linux-x86-64.so.2
          - triple: aarch64-unknown-linux-musl
            runner: linux-arm64-cpu8
            package: openshell-sandbox
            binary: openshell-sandbox
            interpreter: none
          - triple: aarch64-unknown-linux-gnu
            runner: linux-arm64-cpu8
            package: openshell-supervisor
            binary: openshell-supervisor
            interpreter: /lib/ld-linux-aarch64.so.1
    uses: ./.github/workflows/build-binaries.yml
    with:
      package: ${{ matrix.package }}
      binary: ${{ matrix.binary }}
      triple: ${{ matrix.triple }}
      runner: ${{ matrix.runner }}
      cargo-version: ${{ inputs.cargo-version }}
      image-tag: ${{ inputs.image-tag }}
      interpreter: ${{ matrix.interpreter }}
      checkout-ref: ${{ inputs.checkout-ref }}
    secrets: inherit
